# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddRecordScreenTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddRecordScreenUI(object):
    def __init__(self, form) -> None:
        self.setupUi(form)
    
    def setupUi(self, AddRecordScreenUI):
        AddRecordScreenUI.setObjectName("AddRecordScreenUI")
        AddRecordScreenUI.resize(840, 620)
        self.income_label = QtWidgets.QLabel(AddRecordScreenUI)
        self.income_label.setGeometry(QtCore.QRect(190, 30, 67, 17))
        self.income_label.setObjectName("income_label")
        self.outcome_label = QtWidgets.QLabel(AddRecordScreenUI)
        self.outcome_label.setGeometry(QtCore.QRect(180, 80, 67, 17))
        self.outcome_label.setObjectName("outcome_label")
        self.spinBox = QtWidgets.QSpinBox(AddRecordScreenUI)
        self.spinBox.setGeometry(QtCore.QRect(260, 20, 48, 26))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(AddRecordScreenUI)
        self.spinBox_2.setGeometry(QtCore.QRect(260, 70, 48, 26))
        self.spinBox_2.setObjectName("spinBox_2")
        self.sum_label = QtWidgets.QLabel(AddRecordScreenUI)
        self.sum_label.setGeometry(QtCore.QRect(190, 140, 67, 17))
        self.sum_label.setObjectName("sum_label")
        self.textBrowser = QtWidgets.QTextBrowser(AddRecordScreenUI)
        self.textBrowser.setGeometry(QtCore.QRect(260, 130, 81, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.add_pushButton = QtWidgets.QPushButton(AddRecordScreenUI)
        self.add_pushButton.setGeometry(QtCore.QRect(380, 570, 89, 25))
        self.add_pushButton.setObjectName("add_pushButton")
        self.back_pushButton = QtWidgets.QPushButton(AddRecordScreenUI)
        self.back_pushButton.setGeometry(QtCore.QRect(180, 570, 89, 25))
        self.back_pushButton.setObjectName("back_pushButton")
        self.transport_pushButton = QtWidgets.QPushButton(AddRecordScreenUI)
        self.transport_pushButton.setGeometry(QtCore.QRect(180, 240, 101, 25))
        self.transport_pushButton.setObjectName("transport_pushButton")
        self.coffee_pushButton = QtWidgets.QPushButton(AddRecordScreenUI)
        self.coffee_pushButton.setGeometry(QtCore.QRect(180, 300, 89, 25))
        self.coffee_pushButton.setObjectName("coffee_pushButton")
        self.clothes_pushButton = QtWidgets.QPushButton(AddRecordScreenUI)
        self.clothes_pushButton.setGeometry(QtCore.QRect(410, 240, 89, 25))
        self.clothes_pushButton.setObjectName("clothes_pushButton")
        self.groceries_pushButton = QtWidgets.QPushButton(AddRecordScreenUI)
        self.groceries_pushButton.setGeometry(QtCore.QRect(300, 240, 91, 25))
        self.groceries_pushButton.setObjectName("groceries_pushButton")
        self.entertainment_pushButton = QtWidgets.QPushButton(AddRecordScreenUI)
        self.entertainment_pushButton.setGeometry(QtCore.QRect(290, 300, 121, 25))
        self.entertainment_pushButton.setObjectName("entertainment_pushButton")
        self.other_pushButton = QtWidgets.QPushButton(AddRecordScreenUI)
        self.other_pushButton.setGeometry(QtCore.QRect(430, 300, 89, 25))
        self.other_pushButton.setObjectName("other_pushButton")

        self.retranslateUi(AddRecordScreenUI)
        QtCore.QMetaObject.connectSlotsByName(AddRecordScreenUI)

    def retranslateUi(self, AddRecordScreenUI):
        _translate = QtCore.QCoreApplication.translate
        AddRecordScreenUI.setWindowTitle(_translate("AddRecordScreenUI", "Form"))
        self.income_label.setText(_translate("AddRecordScreenUI", "ДОХОД:"))
        self.outcome_label.setText(_translate("AddRecordScreenUI", "РАСХОД:"))
        self.sum_label.setText(_translate("AddRecordScreenUI", "СУММА:"))
        self.add_pushButton.setText(_translate("AddRecordScreenUI", "ДОБАВИТЬ"))
        self.back_pushButton.setText(_translate("AddRecordScreenUI", "НАЗАД"))
        self.transport_pushButton.setText(_translate("AddRecordScreenUI", "ТРАНСПОРТ"))
        self.coffee_pushButton.setText(_translate("AddRecordScreenUI", "КАФЕ"))
        self.clothes_pushButton.setText(_translate("AddRecordScreenUI", "ОДЕЖДА"))
        self.groceries_pushButton.setText(_translate("AddRecordScreenUI", "ПРОДУКТЫ"))
        self.entertainment_pushButton.setText(_translate("AddRecordScreenUI", "РАЗВЛЕЧЕНИЯ"))
        self.other_pushButton.setText(_translate("AddRecordScreenUI", "ДРУГОЕ"))
