# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangeRecordEnterScreenTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeRecordEnterScreenUI(object):
    def __init__(self, form) -> None:
        self.setupUi(form)
    
    def setupUi(self, ChangeRecordEnterScreenUI):
        ChangeRecordEnterScreenUI.setObjectName("ChangeRecordEnterScreenUI")
        ChangeRecordEnterScreenUI.resize(840, 620)
        self.income_label = QtWidgets.QLabel(ChangeRecordEnterScreenUI)
        self.income_label.setGeometry(QtCore.QRect(100, 30, 67, 17))
        self.income_label.setObjectName("income_label")
        self.outcome_label = QtWidgets.QLabel(ChangeRecordEnterScreenUI)
        self.outcome_label.setGeometry(QtCore.QRect(100, 80, 67, 17))
        self.outcome_label.setObjectName("outcome_label")
        self.scrollArea = QtWidgets.QScrollArea(ChangeRecordEnterScreenUI)
        self.scrollArea.setGeometry(QtCore.QRect(100, 130, 571, 80))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 78))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.transport_pushButton = QtWidgets.QPushButton(ChangeRecordEnterScreenUI)
        self.transport_pushButton.setGeometry(QtCore.QRect(108, 270, 101, 25))
        self.transport_pushButton.setObjectName("transport_pushButton")
        self.other_pushButton = QtWidgets.QPushButton(ChangeRecordEnterScreenUI)
        self.other_pushButton.setGeometry(QtCore.QRect(360, 330, 89, 25))
        self.other_pushButton.setObjectName("other_pushButton")
        self.entertainment_pushButton = QtWidgets.QPushButton(ChangeRecordEnterScreenUI)
        self.entertainment_pushButton.setGeometry(QtCore.QRect(220, 330, 121, 25))
        self.entertainment_pushButton.setObjectName("entertainment_pushButton")
        self.coffee_pushButton = QtWidgets.QPushButton(ChangeRecordEnterScreenUI)
        self.coffee_pushButton.setGeometry(QtCore.QRect(110, 330, 89, 25))
        self.coffee_pushButton.setObjectName("coffee_pushButton")
        self.clothes_pushButton = QtWidgets.QPushButton(ChangeRecordEnterScreenUI)
        self.clothes_pushButton.setGeometry(QtCore.QRect(360, 270, 89, 25))
        self.clothes_pushButton.setObjectName("clothes_pushButton")
        self.grosseries_pushButton = QtWidgets.QPushButton(ChangeRecordEnterScreenUI)
        self.grosseries_pushButton.setGeometry(QtCore.QRect(240, 270, 89, 25))
        self.grosseries_pushButton.setObjectName("grosseries_pushButton")
        self.change_pushButton = QtWidgets.QPushButton(ChangeRecordEnterScreenUI)
        self.change_pushButton.setGeometry(QtCore.QRect(210, 570, 89, 25))
        self.change_pushButton.setObjectName("change_pushButton")
        self.back_pushButton = QtWidgets.QPushButton(ChangeRecordEnterScreenUI)
        self.back_pushButton.setGeometry(QtCore.QRect(100, 570, 89, 25))
        self.back_pushButton.setObjectName("back_pushButton")
        self.spinBox = QtWidgets.QSpinBox(ChangeRecordEnterScreenUI)
        self.spinBox.setGeometry(QtCore.QRect(180, 30, 48, 26))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(ChangeRecordEnterScreenUI)
        self.spinBox_2.setGeometry(QtCore.QRect(180, 80, 48, 26))
        self.spinBox_2.setObjectName("spinBox_2")

        self.retranslateUi(ChangeRecordEnterScreenUI)
        QtCore.QMetaObject.connectSlotsByName(ChangeRecordEnterScreenUI)

    def retranslateUi(self, ChangeRecordEnterScreenUI):
        _translate = QtCore.QCoreApplication.translate
        ChangeRecordEnterScreenUI.setWindowTitle(_translate("ChangeRecordEnterScreenUI", "Form"))
        self.income_label.setText(_translate("ChangeRecordEnterScreenUI", "ДОХОД:"))
        self.outcome_label.setText(_translate("ChangeRecordEnterScreenUI", "РАСХОД:"))
        self.transport_pushButton.setText(_translate("ChangeRecordEnterScreenUI", "ТРАНСПОРТ"))
        self.other_pushButton.setText(_translate("ChangeRecordEnterScreenUI", "ДРУГОЕ"))
        self.entertainment_pushButton.setText(_translate("ChangeRecordEnterScreenUI", "РАЗВЛЕЧЕНИЯ"))
        self.coffee_pushButton.setText(_translate("ChangeRecordEnterScreenUI", "КАФЕ"))
        self.clothes_pushButton.setText(_translate("ChangeRecordEnterScreenUI", "ОДЕЖДА"))
        self.grosseries_pushButton.setText(_translate("ChangeRecordEnterScreenUI", "ПРОДУКТЫ"))
        self.change_pushButton.setText(_translate("ChangeRecordEnterScreenUI", "ИЗМЕНИТЬ"))
        self.back_pushButton.setText(_translate("ChangeRecordEnterScreenUI", "НАЗАД"))
