# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangeRecordScreenTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeRecordScreenUI(object):
    def __init__(self, form) -> None:
        self.setupUi(form)
    
    def setupUi(self, ChangeRecordScreenUI):
        ChangeRecordScreenUI.setObjectName("ChangeRecordScreenUI")
        ChangeRecordScreenUI.resize(840, 620)
        self.all_records_label = QtWidgets.QLabel(ChangeRecordScreenUI)
        self.all_records_label.setGeometry(QtCore.QRect(360, 20, 101, 17))
        self.all_records_label.setObjectName("all_records_label")
        self.all_records_scrollArea = QtWidgets.QScrollArea(ChangeRecordScreenUI)
        self.all_records_scrollArea.setGeometry(QtCore.QRect(150, 60, 481, 501))
        self.all_records_scrollArea.setWidgetResizable(True)
        self.all_records_scrollArea.setObjectName("all_records_scrollArea")
        self.all_records_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.all_records_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 499))
        self.all_records_scrollAreaWidgetContents.setObjectName("all_records_scrollAreaWidgetContents")
        self.all_records_scrollArea.setWidget(self.all_records_scrollAreaWidgetContents)
        self.back_pushButton = QtWidgets.QPushButton(ChangeRecordScreenUI)
        self.back_pushButton.setGeometry(QtCore.QRect(300, 580, 89, 25))
        self.back_pushButton.setObjectName("back_pushButton")
        self.change_pushButton = QtWidgets.QPushButton(ChangeRecordScreenUI)
        self.change_pushButton.setGeometry(QtCore.QRect(490, 580, 89, 25))
        self.change_pushButton.setObjectName("change_pushButton")

        self.retranslateUi(ChangeRecordScreenUI)
        QtCore.QMetaObject.connectSlotsByName(ChangeRecordScreenUI)

    def retranslateUi(self, ChangeRecordScreenUI):
        _translate = QtCore.QCoreApplication.translate
        ChangeRecordScreenUI.setWindowTitle(_translate("ChangeRecordScreenUI", "Form"))
        self.all_records_label.setText(_translate("ChangeRecordScreenUI", "ВСЕ ЗАПИСИ"))
        self.back_pushButton.setText(_translate("ChangeRecordScreenUI", "НАЗАД"))
        self.change_pushButton.setText(_translate("ChangeRecordScreenUI", "ИЗМЕНИТЬ"))
