# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteRecordScreenTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteRecordScreenUI(object):
    def __init__(self, form) -> None:
        self.setupUi(form)
    
    def setupUi(self, DeleteRecordScreenUI):
        DeleteRecordScreenUI.setObjectName("DeleteRecordScreenUI")
        DeleteRecordScreenUI.resize(840, 620)
        self.all_record_scrollArea = QtWidgets.QScrollArea(DeleteRecordScreenUI)
        self.all_record_scrollArea.setGeometry(QtCore.QRect(210, 70, 401, 401))
        self.all_record_scrollArea.setWidgetResizable(True)
        self.all_record_scrollArea.setObjectName("all_record_scrollArea")
        self.all_record_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.all_record_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 399, 399))
        self.all_record_scrollAreaWidgetContents.setObjectName("all_record_scrollAreaWidgetContents")
        self.all_record_scrollArea.setWidget(self.all_record_scrollAreaWidgetContents)
        self.all_record_label = QtWidgets.QLabel(DeleteRecordScreenUI)
        self.all_record_label.setGeometry(QtCore.QRect(360, 30, 101, 17))
        self.all_record_label.setObjectName("all_record_label")
        self.back_pushButton = QtWidgets.QPushButton(DeleteRecordScreenUI)
        self.back_pushButton.setGeometry(QtCore.QRect(290, 500, 89, 25))
        self.back_pushButton.setObjectName("back_pushButton")
        self.delete_pushButton = QtWidgets.QPushButton(DeleteRecordScreenUI)
        self.delete_pushButton.setGeometry(QtCore.QRect(440, 500, 89, 25))
        self.delete_pushButton.setObjectName("delete_pushButton")

        self.retranslateUi(DeleteRecordScreenUI)
        QtCore.QMetaObject.connectSlotsByName(DeleteRecordScreenUI)

    def retranslateUi(self, DeleteRecordScreenUI):
        _translate = QtCore.QCoreApplication.translate
        DeleteRecordScreenUI.setWindowTitle(_translate("DeleteRecordScreenUI", "Form"))
        self.all_record_label.setText(_translate("DeleteRecordScreenUI", "ВСЕ ЗАПИСИ"))
        self.back_pushButton.setText(_translate("DeleteRecordScreenUI", "НАЗАД"))
        self.delete_pushButton.setText(_translate("DeleteRecordScreenUI", "УДАЛИТЬ"))
