# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegistrationScreenTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationScreenUI(object):
    def __init__(self, form) -> None:
        self.setupUi(form)
    
    def setupUi(self, RegistrationScreenUI):
        RegistrationScreenUI.setObjectName("RegistrationScreenUI")
        RegistrationScreenUI.resize(840, 620)
        self.create_account_label = QtWidgets.QLabel(RegistrationScreenUI)
        self.create_account_label.setGeometry(QtCore.QRect(330, 20, 141, 17))
        self.create_account_label.setObjectName("create_account_label")
        self.name_lineEdit = QtWidgets.QLineEdit(RegistrationScreenUI)
        self.name_lineEdit.setGeometry(QtCore.QRect(350, 60, 113, 25))
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(RegistrationScreenUI)
        self.password_lineEdit.setGeometry(QtCore.QRect(350, 140, 113, 25))
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(RegistrationScreenUI)
        self.lineEdit_3.setGeometry(QtCore.QRect(350, 100, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.name_label = QtWidgets.QLabel(RegistrationScreenUI)
        self.name_label.setGeometry(QtCore.QRect(270, 60, 67, 17))
        self.name_label.setObjectName("name_label")
        self.email_label = QtWidgets.QLabel(RegistrationScreenUI)
        self.email_label.setGeometry(QtCore.QRect(260, 100, 67, 17))
        self.email_label.setObjectName("email_label")
        self.password_label = QtWidgets.QLabel(RegistrationScreenUI)
        self.password_label.setGeometry(QtCore.QRect(260, 150, 71, 17))
        self.password_label.setObjectName("password_label")
        self.crete_account_pushButton = QtWidgets.QPushButton(RegistrationScreenUI)
        self.crete_account_pushButton.setGeometry(QtCore.QRect(330, 200, 151, 25))
        self.crete_account_pushButton.setObjectName("crete_account_pushButton")

        self.retranslateUi(RegistrationScreenUI)
        QtCore.QMetaObject.connectSlotsByName(RegistrationScreenUI)

    def retranslateUi(self, RegistrationScreenUI):
        _translate = QtCore.QCoreApplication.translate
        RegistrationScreenUI.setWindowTitle(_translate("RegistrationScreenUI", "Form"))
        self.create_account_label.setText(_translate("RegistrationScreenUI", "СОЗДАТЬ АККАУНТ"))
        self.name_label.setText(_translate("RegistrationScreenUI", "ИМЯ:"))
        self.email_label.setText(_translate("RegistrationScreenUI", "ПОЧТА:"))
        self.password_label.setText(_translate("RegistrationScreenUI", "ПАРОЛЬ:"))
        self.crete_account_pushButton.setText(_translate("RegistrationScreenUI", "СОЗДАТЬ АККАУНТ"))
