# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelfCabinetTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelfCabinetUI(object):
    def __init__(self, form) -> None:
        self.setupUi(form)
    
    def setupUi(self, SelfCabinetUI):
        SelfCabinetUI.setObjectName("SelfCabinetUI")
        SelfCabinetUI.resize(840, 620)
        self.add_record_pushButton = QtWidgets.QPushButton(SelfCabinetUI)
        self.add_record_pushButton.setGeometry(QtCore.QRect(330, 30, 151, 25))
        self.add_record_pushButton.setObjectName("add_record_pushButton")
        self.show_record_pushButton = QtWidgets.QPushButton(SelfCabinetUI)
        self.show_record_pushButton.setGeometry(QtCore.QRect(320, 160, 181, 25))
        self.show_record_pushButton.setObjectName("show_record_pushButton")
        self.delete_record_pushButton = QtWidgets.QPushButton(SelfCabinetUI)
        self.delete_record_pushButton.setGeometry(QtCore.QRect(330, 110, 151, 25))
        self.delete_record_pushButton.setObjectName("delete_record_pushButton")
        self.edit_record_pushButton = QtWidgets.QPushButton(SelfCabinetUI)
        self.edit_record_pushButton.setGeometry(QtCore.QRect(330, 70, 151, 25))
        self.edit_record_pushButton.setObjectName("edit_record_pushButton")
        self.my_account_pushButton = QtWidgets.QPushButton(SelfCabinetUI)
        self.my_account_pushButton.setGeometry(QtCore.QRect(340, 210, 131, 41))
        self.my_account_pushButton.setObjectName("my_account_pushButton")

        self.retranslateUi(SelfCabinetUI)
        QtCore.QMetaObject.connectSlotsByName(SelfCabinetUI)

    def retranslateUi(self, SelfCabinetUI):
        _translate = QtCore.QCoreApplication.translate
        SelfCabinetUI.setWindowTitle(_translate("SelfCabinetUI", "Form"))
        self.add_record_pushButton.setText(_translate("SelfCabinetUI", "ДОБАВИТЬ ЗАПИСЬ"))
        self.show_record_pushButton.setText(_translate("SelfCabinetUI", "ПРОСМОТРЕТЬ ЗАПИСЬ"))
        self.delete_record_pushButton.setText(_translate("SelfCabinetUI", "УДАЛИТЬ ЗАПИСЬ"))
        self.edit_record_pushButton.setText(_translate("SelfCabinetUI", "ИЗМЕНИТЬ ЗАПИСЬ"))
        self.my_account_pushButton.setText(_translate("SelfCabinetUI", "МОЙ АККАУНТ"))
