# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowRecordScreenTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowRecordScreenUI(object):
    def __init__(self, form) -> None:
        self.setupUi(form)
    
    def setupUi(self, ShowRecordScreenUI):
        ShowRecordScreenUI.setObjectName("ShowRecordScreenUI")
        ShowRecordScreenUI.resize(840, 620)
        self.all_labels_label = QtWidgets.QLabel(ShowRecordScreenUI)
        self.all_labels_label.setGeometry(QtCore.QRect(370, 20, 101, 17))
        self.all_labels_label.setObjectName("all_labels_label")
        self.all_labels_scrollArea = QtWidgets.QScrollArea(ShowRecordScreenUI)
        self.all_labels_scrollArea.setGeometry(QtCore.QRect(200, 70, 421, 401))
        self.all_labels_scrollArea.setWidgetResizable(True)
        self.all_labels_scrollArea.setObjectName("all_labels_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 419, 399))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.all_labels_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.back_pushButton = QtWidgets.QPushButton(ShowRecordScreenUI)
        self.back_pushButton.setGeometry(QtCore.QRect(200, 510, 89, 25))
        self.back_pushButton.setObjectName("back_pushButton")

        self.retranslateUi(ShowRecordScreenUI)
        QtCore.QMetaObject.connectSlotsByName(ShowRecordScreenUI)

    def retranslateUi(self, ShowRecordScreenUI):
        _translate = QtCore.QCoreApplication.translate
        ShowRecordScreenUI.setWindowTitle(_translate("ShowRecordScreenUI", "Form"))
        self.all_labels_label.setText(_translate("ShowRecordScreenUI", "ВСЕ ЗАПИСИ"))
        self.back_pushButton.setText(_translate("ShowRecordScreenUI", "НАЗАД"))
