# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserScreenTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserScreenUI(object):
    def __init__(self, form) -> None:
        self.setupUi(form)
    
    def setupUi(self, UserScreenUI):
        UserScreenUI.setObjectName("UserScreenUI")
        UserScreenUI.resize(840, 620)
        self.family_budget_manager_label = QtWidgets.QLabel(UserScreenUI)
        self.family_budget_manager_label.setGeometry(QtCore.QRect(290, 20, 261, 17))
        self.family_budget_manager_label.setObjectName("family_budget_manager_label")
        self.registration_pushButton = QtWidgets.QPushButton(UserScreenUI)
        self.registration_pushButton.setGeometry(QtCore.QRect(350, 60, 121, 25))
        self.registration_pushButton.setObjectName("registration_pushButton")
        self.enter_pushButton = QtWidgets.QPushButton(UserScreenUI)
        self.enter_pushButton.setGeometry(QtCore.QRect(350, 100, 121, 25))
        self.enter_pushButton.setObjectName("enter_pushButton")

        self.retranslateUi(UserScreenUI)
        QtCore.QMetaObject.connectSlotsByName(UserScreenUI)

    def retranslateUi(self, UserScreenUI):
        _translate = QtCore.QCoreApplication.translate
        UserScreenUI.setWindowTitle(_translate("UserScreenUI", "Form"))
        self.family_budget_manager_label.setText(_translate("UserScreenUI", "МЕНЕДЖЕР СЕМЕЙНОГО БЮДЖЕТА"))
        self.registration_pushButton.setText(_translate("UserScreenUI", "РЕГИСТРАЦИЯ"))
        self.enter_pushButton.setText(_translate("UserScreenUI", "ВОЙТИ"))
